package crm.post.domain;
// Generated 2017-6-7 11:09:42 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import crm.dep.domain.CrmDepartment;

/**
 * CrmPost generated by hbm2java
 */
public class CrmPost implements java.io.Serializable {

	private String postId;
	private String postName;
	private CrmDepartment crmDepartment;
	private Set crmStaffs = new HashSet(0);

	public CrmPost() {
	}

	public CrmPost(String postId) {
		this.postId = postId;
	}

	public CrmPost(String postId, CrmDepartment crmDepartment, String postName, Set crmStaffs) {
		this.postId = postId;
		this.crmDepartment = crmDepartment;
		this.postName = postName;
		// this.crmStaffs = crmStaffs;
	}

	public String getPostId() {
		return this.postId;
	}

	public void setPostId(String postId) {
		this.postId = postId;
	}

	public CrmDepartment getCrmDepartment() {
		return this.crmDepartment;
	}

	public void setCrmDepartment(CrmDepartment crmDepartment) {
		this.crmDepartment = crmDepartment;
	}

	public String getPostName() {
		return this.postName;
	}

	public void setPostName(String postName) {
		this.postName = postName;
	}

	public Set getCrmStaffs() {
		return this.crmStaffs;
	}

	public void setCrmStaffs(Set crmStaffs) {
		this.crmStaffs = crmStaffs;
	}

	@Override
	public String toString() {
		return "CrmPost [postId=" + postId + ", postName=" + postName + ", crmDepartment=" + crmDepartment + "]";
	}

	
}
