package crm.staff.domain;
// Generated 2017-6-7 11:09:42 by Hibernate Tools 5.2.3.Final

import java.util.Date;

import crm.post.domain.CrmPost;

/**
 * CrmStaff generated by hbm2java
 */
public class CrmStaff implements java.io.Serializable {

	private String staffId;
	private String loginName;
	private String loginPwd;
	private String staffName;
	private String gender;
	private Date onDutyDate;
	
	private CrmPost crmPost;

	public CrmStaff() {
	}

	public CrmStaff(String staffId) {
		this.staffId = staffId;
	}

	public CrmStaff(String staffId, CrmPost crmPost, String loginName, String loginPwd, String staffName, String gender,
			Date onDutyDate) {
		this.staffId = staffId;
		this.crmPost = crmPost;
		this.loginName = loginName;
		this.loginPwd = loginPwd;
		this.staffName = staffName;
		this.gender = gender;
		this.onDutyDate = onDutyDate;
	}

	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	public CrmPost getCrmPost() {
		return this.crmPost;
	}

	public void setCrmPost(CrmPost crmPost) {
		this.crmPost = crmPost;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getLoginPwd() {
		return this.loginPwd;
	}

	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getOnDutyDate() {
		return this.onDutyDate;
	}

	public void setOnDutyDate(Date onDutyDate) {
		this.onDutyDate = onDutyDate;
	}

	@Override
	public String toString() {
		return "CrmStaff [staffId=" + staffId + ", loginName=" + loginName + ", loginPwd=" + loginPwd + ", staffName="
				+ staffName + ", gender=" + gender + ", onDutyDate=" + onDutyDate + ", crmPost=" + crmPost + "]";
	}
	
}
