package crm.clazz.domain;
// Generated 2017-6-7 11:09:42 by Hibernate Tools 5.2.3.Final

import java.util.Date;

import crm.course.domain.CrmCourseType;

/**
 * CrmClass generated by hbm2java
 */
public class CrmClass implements java.io.Serializable {

	private String classId;
	private String name;
	private Date beginTime;
	private Date endTime;
	private String status;
	private Integer totalCount;
	private Integer upgradeCount;
	private Integer changeCount;
	private Integer runoffCount;
	private String remark;
	private Date uploadTime;
	private String uploadPath;
	private String uploadFilename;
	private CrmCourseType crmCourseType;

	public CrmClass() {
	}

	public CrmClass(String classId) {
		this.classId = classId;
	}

	public CrmClass(String classId, CrmCourseType crmCourseType, String name, Date beginTime, Date endTime,
			String status, Integer totalCount, Integer upgradeCount, Integer changeCount, Integer runoffCount,
			String remark, Date uploadTime, String uploadPath, String uploadFilename) {
		this.classId = classId;
		this.crmCourseType = crmCourseType;
		this.name = name;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.status = status;
		this.totalCount = totalCount;
		this.upgradeCount = upgradeCount;
		this.changeCount = changeCount;
		this.runoffCount = runoffCount;
		this.remark = remark;
		this.uploadTime = uploadTime;
		this.uploadPath = uploadPath;
		this.uploadFilename = uploadFilename;
	}

	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	public CrmCourseType getCrmCourseType() {
		return this.crmCourseType;
	}

	public void setCrmCourseType(CrmCourseType crmCourseType) {
		this.crmCourseType = crmCourseType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(Integer totalCount) {
		this.totalCount = totalCount;
	}

	public Integer getUpgradeCount() {
		return this.upgradeCount;
	}

	public void setUpgradeCount(Integer upgradeCount) {
		this.upgradeCount = upgradeCount;
	}

	public Integer getChangeCount() {
		return this.changeCount;
	}

	public void setChangeCount(Integer changeCount) {
		this.changeCount = changeCount;
	}

	public Integer getRunoffCount() {
		return this.runoffCount;
	}

	public void setRunoffCount(Integer runoffCount) {
		this.runoffCount = runoffCount;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public String getUploadPath() {
		return this.uploadPath;
	}

	public void setUploadPath(String uploadPath) {
		this.uploadPath = uploadPath;
	}

	public String getUploadFilename() {
		return this.uploadFilename;
	}

	public void setUploadFilename(String uploadFilename) {
		this.uploadFilename = uploadFilename;
	}

	@Override
	public String toString() {
		return "CrmClass [classId=" + classId + ", name=" + name + ", beginTime=" + beginTime + ", endTime=" + endTime
				+ ", status=" + status + ", totalCount=" + totalCount + ", upgradeCount=" + upgradeCount
				+ ", changeCount=" + changeCount + ", runoffCount=" + runoffCount + ", remark=" + remark
				+ ", uploadTime=" + uploadTime + ", uploadPath=" + uploadPath + ", uploadFilename=" + uploadFilename
				+ ", crmCourseType=" + crmCourseType + "]";
	}

}
